version = 1

test_patterns = [
  "tests/**",
  "**/*_test.go"
]

exclude_patterns = [
  "examples/**"
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_path = "github.com/SAP/go-ase"
